<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20161207092130 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE sandstorm_monitoring404_domain_model_requestwhichtriggered404 (persistence_object_identifier VARCHAR(40) NOT NULL, method VARCHAR(255) NOT NULL, scheme VARCHAR(255) NOT NULL, host VARCHAR(255) NOT NULL, port INT DEFAULT NULL, path VARCHAR(255) NOT NULL, query VARCHAR(255) DEFAULT NULL, firsthitdate DATETIME NOT NULL, lasthitdate DATETIME NOT NULL, status VARCHAR(255) NOT NULL, numberofhits INT NOT NULL, INDEX requeststatus (status), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('DROP TABLE sandstorm_monitoring404_domain_model_requestwhichtriggered404');
    }
}
